models/base.py
from sqlalchemy.orm import DeclarativeBase

class Base(DeclarativeBase):
    pass

models/book.py
from models.base import Base
from sqlalchemy import Integer, String, Text, DateTime, func
from sqlalchemy.orm import mapped_column, relationship, backref
from sqlalchemy.sql import func


class Book(Base):
    __tablename__ = 'book'

    id = mapped_column(Integer, primary_key=True, autoincrement=True)
    title = mapped_column(String(191), nullable=False)
    price = mapped_column(Integer)
    description = mapped_column(Text)
    created_at = mapped_column(DateTime(timezone=True), server_default=func.now())

    # Relationship list
    reviews= relationship("Review", cascade="all,delete-orphan")

    def __repr__(self):
        return f'<Book {self.name}>'

models/review.py
from models.base import Base
from sqlalchemy import Integer, String, Text, DateTime, ForeignKey
from sqlalchemy.orm import mapped_column
from sqlalchemy.sql import func

class Review(Base):
    __tablename__ = 'book_review'

    id = mapped_column(Integer, primary_key=True)
    book_id = mapped_column(Integer, ForeignKey("book.id", ondelete="CASCADE"))
    email = mapped_column(String(30), nullable= False)
    rating = mapped_column(Integer)
    review_content = mapped_column(Text)
    created_at = mapped_column(DateTime(timezone=True), server_default=func.now())
    
    def __repr__(self):
        return f'<Review {self.id}>'

models/user.py
from models.base import Base
from sqlalchemy import Integer, String, DateTime, func
from sqlalchemy.orm import mapped_column
from sqlalchemy.sql import func
from flask_login import UserMixin
import bcrypt


class User(Base, UserMixin):
    __tablename__ = 'user'

    created_at = mapped_column(DateTime(timezone=True), server_default=func.now())
    id = mapped_column(Integer, primary_key=True, autoincrement=True)
    name = mapped_column(String(100), nullable=False)
    email = mapped_column(String(100), nullable=False)
    password = mapped_column(String(100), nullable=False)
    

    def __repr__(self):
        return f'<User {self.name}>'
    
    # u/ hash atau mengubah password agar ter encrypt
    def set_password(self, password):
        self.password = bcrypt.hashpw(password.encode('utf-8'), bcrypt.gensalt()).decode('utf-8')
    
    # u/ check password login apakah sama dengan yg didatabase
    # password login di hashing dulu lalu disamakan dengan db
    def check_password(self, password):
        return bcrypt.checkpw(password.encode('utf-8'), self.password.encode('utf-8'))

controllers/book.py
from flask import Blueprint, render_template, request
from connectors.mysql_connector import Session, engine
from sqlalchemy.orm import sessionmaker
from models.book import Book
from models.review import Review
from sqlalchemy import select, or_

from flask_login import current_user, login_required

book_routes = Blueprint('book_routes',__name__)

@book_routes.route("/book", methods=['GET'])
@login_required
def book_home():
    response_data = dict()

    connection = engine.connect()
    Session = sessionmaker(connection)
    session = Session()

    try:
        book_query = select(Book)

        if request.args.get('query') != None:
            search_query = request.args.get('query')
            book_query = book_query.where(or_(Book.title.like(f"%{search_query}%"), Book.description.like(f"%{search_query}%")))

        books = session.execute(book_query)
        books = books.scalars()
        response_data['books'] = books
        
    except Exception as e:
        print(e)
        return "Error Processing Data"

    response_data['name'] = current_user.name
    return render_template("books/book_home.html", response_data = response_data)

@book_routes.route("/book/<id>", methods=['GET'])
def book_detail(id):
    response_data = dict()

    session = Session()

    try:
        book = session.query(Book).filter((Book.id==id)).first()
        if (book == None):
            return "Data not found"
        response_data['book'] = book
    except Exception as e:
        print(e)
        return "Error Processing Data"

    return render_template("books/book_detail.html", response_data = response_data)

@book_routes.route("/book", methods=['POST'])
# agar yg bisa akses /product hanya yg sdh login butuh @login_required
@login_required
def book_insert():
    
    new_book = Book(
        title=request.form['title'],
        price=request.form['price'],
        description=request.form['description']
    )

    session = Session()
    session.begin()
    try:
        session.add(new_book)
        session.commit()
    except Exception as e:
        session.rollback()
        return { "message": "Fail to insert data"}

    return { "message": "Success insert data"}

@book_routes.route("/book/<id>", methods=['DELETE'])
def book_delete(id):

    session = Session()
    session.begin()

    try:
        book = session.query(Book).filter(Book.id==id).first()
        session.delete(book)
        session.commit()
    except Exception as e:
        session.rollback()
        print(e)
        return { "message": "Fail to delete data"}
    
    return { "message": "Success delete data"}

@book_routes.route("/book/<id>", methods=['PUT'])
def book_update(id):

    session = Session()
    session.begin()

    try:
        book = session.query(Book).filter(Book.id==id).first()

        book.title = request.form['title']
        book.price = request.form['price']
        book.description = request.form['description']

        session.commit()
    except Exception as e:
        session.rollback()
        return { "message": "Fail to Update data"}
    
    return { "message": "Success updating data"}

controllers/user_login.py
from flask import Blueprint, render_template, request, redirect
from connectors.mysql_connector import engine

from models.user import User
from sqlalchemy import select, or_
from sqlalchemy.orm import sessionmaker
from flask_login import login_user, logout_user

user_routes_login = Blueprint('user_routes_login',__name__)

@user_routes_login.route("/login", methods=['GET'])
def user_login():
    return render_template("users/login.html")

@user_routes_login.route("/login", methods=['POST'])
def do_user_login():
    connection = engine.connect()
    Session = sessionmaker(connection)
    session = Session()

    try:
        user = session.query(User).filter(User.email==request.form['email']).first()

        if user == None:
            return {"message": "email tidak terdaftar"}
        
        # check password 
        if not user.check_password(request.form['password']):
            return {"message": "password salah"}
        
        # u/ menyimpan data user yg berhasil login ke session 
        # lalu dibuatkan session id yg akan dikembalikan ke browser dan disimpan dalam cookie 
        login_user(user, remember = False)
        return redirect('/book')

    except Exception as e:
        return {"message": "login gagal"}
    
@user_routes_login.route("/logout", methods=['GET'])
def do_user_logout():
    logout_user()
    return redirect('/login')

controllers/user_register.py
from flask import Blueprint, render_template, request, redirect
from connectors.mysql_connector import engine
from models.user import User
from sqlalchemy.orm import sessionmaker

user_routes_register = Blueprint('user_routes_register',__name__)

@user_routes_register.route("/register", methods=['GET'])
def user_register():
    return render_template("users/register.html")

@user_routes_register.route("/register", methods=['POST'])
def do_user_registration():

    name = request.form['name']
    email = request.form['email']
    password = request.form['password']

    NewUser = User(name = name, email = email)
    NewUser.set_password(password)

    connection = engine.connect()
    Session = sessionmaker(connection)
    session = Session()

    session.begin()
    try:
        session.add(NewUser)
        session.commit()
    except Exception as e:
        # gagal
        session.rollback()
        return {"message": "Gagal register"}
    return redirect('/login')

templates/books/book_detail.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Book Reviews</title>
    <style>
      table {
        border-collapse: collapse;
        width: 100%;
      }
      th,
      td {
        border: 1px solid #ddd;
        padding: 8px;
        text-align: left;
      }
      th {
        background-color: #f2f2f2;
      }
      tr:nth-child(even) {
        background-color: #f2f2f2;
      }
    </style>
  </head>
  <body>
    <h2>Book Details</h2>
    <a href="{{ url_for('book_routes.book_home') }}">Back</a>

    <div>
      <h3>Book Title: {{ response_data['book'].title }}</h3>
      <p>Price: {{ response_data['book'].price }}</p>
      <p>Rating: {{ response_data['book'].average_rating }}</p>
    </div>

    <h2>Book Reviews</h2>
    <table>
      <thead>
        <tr>
          <th>Email</th>
          <th>Rating</th>
          <th>Review Content</th>
          <th>Created Datetime</th>
        </tr>
      </thead>
      <tbody>
        {% for review in response_data['book'].reviews %}
        <tr>
          <td>{{ review.email }}</td>
          <td>{{ review.rating }}</td>
          <td>{{ review.review_content }}</td>
          <td>{{ review.created_at }}</td>
        </tr>
        {% endfor %}
        <!-- Add more <tr> elements for additional reviews -->
      </tbody>
    </table>
  </body>
</html>

templates/books/book_home.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Book List</title>
    <style>
      table {
        border-collapse: collapse;
        width: 100%;
      }
      th,
      td {
        border: 1px solid #ddd;
        padding: 8px;
        text-align: left;
      }
      th {
        background-color: #f2f2f2;
      }
      tr:nth-child(even) {
        background-color: #f2f2f2;
      }
      button {
        padding: 5px 10px;
        cursor: pointer;
      }
      /* Basic styling for search bar */
      .search-container {
        margin-top: 20px;
      }

      .search-input {
        padding: 10px;
        width: 300px;
        border-radius: 5px;
        border: 1px solid #ccc;
        font-size: 16px;
      }

      .search-button {
        padding: 10px 20px;
        background-color: #007bff;
        color: #fff;
        border: none;
        border-radius: 5px;
        cursor: pointer;
        font-size: 16px;
      }
    </style>
  </head>
  <body>
    <div>
      Hello, {{ response_data ['name'] }}
      <a href="/logout">Logout</a>
    </div>
    <h2>Book List</h2>
    <button onclick="openNewBookForm()">Add New Book</button>
    <div class="search-container">
      <input
        type="text"
        class="search-input"
        id="searchInput"
        placeholder="Search Title..."
      />
      <button class="search-button" onclick="search()">Search</button>
    </div>
    <hr style="border: none" />
    <table>
      <thead>
        <tr>
          <th>ID</th>
          <th>Book Title</th>
          <th>Price</th>
          <th>Description</th>
          <th>Action</th>
        </tr>
      </thead>
      <tbody>
        {% for book in response_data['books'] %}
        <tr>
          <td>{{ book.id }}</td>
          <td id="title_{{ book.id }}">{{ book.title }}</td>
          <td id="price_{{ book.id }}">{{ book.price }}</td>
          <td id="desc_{{ book.id }}">{{ book.description }}</td>
          <td>
            <a href="{{ url_for('book_routes.book_detail', id=book.id) }}"
              >Review</a
            >
            <button onclick="openEditBookForm(this)" id="edit_{{ book.id }}">
              Edit
            </button>
            <button onclick="deleteBook(this)" id="delete_{{ book.id }}">
              Delete
            </button>
          </td>
        </tr>
        {% endfor %}
        <!-- Add more <tr> elements for additional Books -->
      </tbody>
    </table>
    <div id="newBookForm" style="display: none">
      <h3 id="formSection">Add New Book</h3>
      <form id="bookForm">
        <label for="bookTitle">Book Title:</label>
        <input type="text" id="bookTitle" name="bookTitle" /><br /><br />
        <label for="bookPrice">Price:</label>
        <input type="number" id="bookPrice" name="bookPrice" /><br /><br />
        <label for="bookDescription">Description:</label><br />
        <textarea
          id="bookDescription"
          name="bookDescription"
          rows="4"
          cols="50"
        ></textarea
        ><br /><br />
        <button type="button" onclick="submitForm()">Submit</button>
        <button type="button" onclick="closeNewBookForm()">Cancel</button>
      </form>
    </div>
    <script
      src="https://code.jquery.com/jquery-3.7.1.min.js"
      integrity="sha256-/JqT3SQfawRcv/BIHPThkBvs0OEvtFFmqPF/lYI/Cxo="
      crossorigin="anonymous"
    ></script>
    <script>
      var form_url = "";
      var form_method = "";
      var base_url = "{{ url_for('book_routes.book_home') }}";

      function openNewBookForm() {
        form_method = "POST";
        form_url = "{{ url_for('book_routes.book_insert') }}";
        document.getElementById("newBookForm").style.display = "block";
        document.getElementById("formSection").innerHTML = "Add New Book";
        document.getElementById("bookForm").reset();
      }

      function openEditBookForm(button) {
        var selected_book_id = button.id.split("_")[1];
        form_method = "PUT";
        form_url = base_url + "/" + selected_book_id;

        var title = $("#title_" + selected_book_id).html();
        var price = $("#price_" + selected_book_id).html();
        var desc = $("#desc_" + selected_book_id).html();

        $("#bookTitle").val(title);
        $("#bookPrice").val(price);
        $("#bookDescription").val(desc);

        document.getElementById("newBookForm").style.display = "block";
        document.getElementById("formSection").innerHTML = "Edit Book";
      }

      function closeNewBookForm() {
        document.getElementById("newBookForm").style.display = "none";
      }

      function submitForm() {
        var request_data = {
          title: $("#bookTitle").val(),
          price: $("#bookPrice").val(),
          description: $("#bookDescription").val(),
        };

        $.ajax({
          url: form_url,
          data: request_data,
          method: form_method,
        }).done(function (response) {
          alert(response.message);
          location.reload();
        });
      }

      function deleteBook(button) {
        var selected_book_id = button.id.split("_")[1];
        var delete_url = base_url + "/" + selected_book_id;

        $.ajax({
          url: delete_url,
          method: "DELETE",
        }).done(function (response) {
          alert(response.message);
          location.reload();
        });
      }

      function search() {
        window.location = base_url + "?query=" + $("#searchInput").val();
      }
    </script>
  </body>
</html>

templates/products/product_home.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Product List</title>
    <style>
      table {
        border-collapse: collapse;
        width: 100%;
      }
      th,
      td {
        border: 1px solid #ddd;
        padding: 8px;
        text-align: left;
      }
      th {
        background-color: #f2f2f2;
      }
      tr:nth-child(even) {
        background-color: #f2f2f2;
      }
      button {
        padding: 5px 10px;
        cursor: pointer;
      }
      /* Basic styling for search bar */
      .search-container {
        margin-top: 20px;
      }

      .search-input {
        padding: 10px;
        width: 300px;
        border-radius: 5px;
        border: 1px solid #ccc;
        font-size: 16px;
      }

      .search-button {
        padding: 10px 20px;
        background-color: #007bff;
        color: #fff;
        border: none;
        border-radius: 5px;
        cursor: pointer;
        font-size: 16px;
      }
    </style>
  </head>
  <body>
    <div>
      Hello, {{ response_data ['name'] }}
      <a href="/logout">Logout</a>
    </div>
    <h2>Product List</h2>
    <button onclick="openNewProductForm()">Add New Product</button>
    <div class="search-container">
      <input
        type="text"
        class="search-input"
        id="searchInput"
        placeholder="Search..."
      />
      <button class="search-button" onclick="search()">Search</button>
    </div>
    <hr style="border: none" />
    <table>
      <thead>
        <tr>
          <th>ID</th>
          <th>Name</th>
          <th>Price</th>
          <th>Description</th>
          <th>Action</th>
        </tr>
      </thead>
      <tbody>
        {% for product in response_data['products'] %}
        <tr>
          <td>{{ product.id }}</td>
          <td id="name_{{ product.id }}">{{ product.name }}</td>
          <td id="price_{{ product.id }}">{{ product.price }}</td>
          <td id="desc_{{ product.id }}">{{ product.description }}</td>
          <td>
            <a
              href="{{ url_for('product_routes.product_detail', id=product.id) }}"
              >Review</a
            >
            <button
              onclick="openEditProductForm(this)"
              id="edit_{{ product.id }}"
            >
              Edit
            </button>
            <button onclick="deleteProduct(this)" id="delete_{{ product.id }}">
              Delete
            </button>
          </td>
        </tr>
        {% endfor %}
        <!-- Add more <tr> elements for additional products -->
      </tbody>
    </table>
    <div id="newProductForm" style="display: none">
      <h3 id="formSection">Add New Product</h3>
      <form id="productForm">
        <label for="productName">Product Name:</label>
        <input type="text" id="productName" name="productName" /><br /><br />
        <label for="productPrice">Price:</label>
        <input
          type="number"
          id="productPrice"
          name="productPrice"
        /><br /><br />
        <label for="productDescription">Description:</label><br />
        <textarea
          id="productDescription"
          name="productDescription"
          rows="4"
          cols="50"
        ></textarea
        ><br /><br />
        <button type="button" onclick="submitForm()">Submit</button>
        <button type="button" onclick="closeNewProductForm()">Cancel</button>
      </form>
    </div>
    <script
      src="https://code.jquery.com/jquery-3.7.1.min.js"
      integrity="sha256-/JqT3SQfawRcv/BIHPThkBvs0OEvtFFmqPF/lYI/Cxo="
      crossorigin="anonymous"
    ></script>
    <script>
      var form_url = "";
      var form_method = "";
      var base_url = "{{ url_for('product_routes.product_home') }}";

      function openNewProductForm() {
        form_method = "POST";
        form_url = "{{ url_for('product_routes.product_insert') }}";
        document.getElementById("newProductForm").style.display = "block";
        document.getElementById("formSection").innerHTML = "Add New Product";
        document.getElementById("productForm").reset();
      }

      function openEditProductForm(button) {
        var selected_product_id = button.id.split("_")[1];
        form_method = "PUT";
        form_url = base_url + "/" + selected_product_id;

        var name = $("#name_" + selected_product_id).html();
        var price = $("#price_" + selected_product_id).html();
        var desc = $("#desc_" + selected_product_id).html();

        $("#productName").val(name);
        $("#productPrice").val(price);
        $("#productDescription").val(desc);

        document.getElementById("newProductForm").style.display = "block";
        document.getElementById("formSection").innerHTML = "Edit Product";
      }

      function closeNewProductForm() {
        document.getElementById("newProductForm").style.display = "none";
      }

      function submitForm() {
        var request_data = {
          name: $("#productName").val(),
          price: $("#productPrice").val(),
          description: $("#productDescription").val(),
        };

        $.ajax({
          url: form_url,
          data: request_data,
          method: form_method,
        }).done(function (response) {
          alert(response.message);
          location.reload();
        });
      }

      function deleteProduct(button) {
        var selected_product_id = button.id.split("_")[1];
        var delete_url = base_url + "/" + selected_product_id;

        $.ajax({
          url: delete_url,
          method: "DELETE",
        }).done(function (response) {
          alert(response.message);
          location.reload();
        });
      }

      function search() {
        window.location = base_url + "?query=" + $("#searchInput").val();
      }
    </script>
  </body>
</html>

templates/reviews/review_create.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Review Form</title>
    <style>
      label {
        display: block;
        margin-bottom: 10px;
      }
      input[type="text"],
      select,
      textarea {
        width: 100%;
        padding: 8px;
        margin-bottom: 20px;
        border: 1px solid #ccc;
        border-radius: 4px;
        box-sizing: border-box;
      }
      input[type="submit"] {
        background-color: #4caf50;
        color: white;
        padding: 10px 20px;
        border: none;
        border-radius: 4px;
        cursor: pointer;
      }
      input[type="submit"]:hover {
        background-color: #45a049;
      }
    </style>
  </head>
  <body>
    <h2>Review Form</h2>
    <form action="#" method="post">
      <label for="book">Select Book:</label>
      <select id="book" name="book">
        <option value="book1">Book 1</option>
        <option value="book2">Book 2</option>
        <option value="book3">Book 3</option>
        <!-- Add more book options if needed -->
      </select>

      <label for="email">Email:</label>
      <input type="text" id="email" name="email" required />

      <label for="rating">Rating:</label>
      <input type="number" id="rating" name="rating" min="1" max="5" required />

      <label for="description">Description:</label>
      <textarea
        id="description"
        name="description"
        rows="4"
        required
      ></textarea>

      <input type="submit" value="Submit Review" />
    </form>
  </body>
</html>

templates/users/login.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>User Login</title>
    <style>
      body {
        font-family: Arial, sans-serif;
        margin: 0;
        padding: 0;
        background-color: #f2f2f2;
      }
      .container {
        max-width: 400px;
        margin: 50px auto;
        padding: 20px;
        background-color: #fff;
        border-radius: 5px;
        box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
      }
      .form-group {
        margin-bottom: 20px;
      }
      label {
        display: block;
        font-weight: bold;
        margin-bottom: 5px;
      }
      input[type="email"],
      input[type="password"] {
        width: 100%;
        padding: 10px;
        border: 1px solid #ccc;
        border-radius: 5px;
        box-sizing: border-box;
      }
      input[type="submit"] {
        background-color: #007bff;
        color: #fff;
        padding: 10px 20px;
        border: none;
        border-radius: 5px;
        cursor: pointer;
      }
      input[type="submit"]:hover {
        background-color: #0056b3;
      }
    </style>
  </head>
  <body>
    <div class="container">
      <h2>User Login</h2>
      <form
        action="{{ url_for('user_routes_login.do_user_login') }}"
        method="POST"
      >
        <div class="form-group">
          <label for="email">Email:</label>
          <input type="email" id="email" name="email" required />
        </div>
        <div class="form-group">
          <label for="password">Password:</label>
          <input type="password" id="password" name="password" required />
        </div>
        <input type="submit" value="Login" />
      </form>
    </div>
  </body>
</html>

templates/users/register.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>User Registration</title>
    <style>
      body {
        font-family: Arial, sans-serif;
        margin: 0;
        padding: 0;
        background-color: #f2f2f2;
      }
      .container {
        max-width: 400px;
        margin: 50px auto;
        padding: 20px;
        background-color: #fff;
        border-radius: 5px;
        box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
      }
      .form-group {
        margin-bottom: 20px;
      }
      label {
        display: block;
        font-weight: bold;
        margin-bottom: 5px;
      }
      input[type="text"],
      input[type="email"],
      input[type="password"] {
        width: 100%;
        padding: 10px;
        border: 1px solid #ccc;
        border-radius: 5px;
        box-sizing: border-box;
      }
      input[type="submit"] {
        background-color: #007bff;
        color: #fff;
        padding: 10px 20px;
        border: none;
        border-radius: 5px;
        cursor: pointer;
      }
      input[type="submit"]:hover {
        background-color: #0056b3;
      }
    </style>
  </head>
  <body>
    <div class="container">
      <h2>User Registration</h2>
      <form
        action="{{ url_for('user_routes_register.do_user_registration') }}"
        method="POST"
      >
        <div class="form-group">
          <label for="name">Name:</label>
          <input type="text" id="name" name="name" required />
        </div>
        <div class="form-group">
          <label for="email">Email:</label>
          <input type="email" id="email" name="email" required />
        </div>
        <div class="form-group">
          <label for="password">Password:</label>
          <input type="password" id="password" name="password" required />
        </div>
        <input type="submit" value="Register" />
      </form>
    </div>
  </body>
</html>